mumuki/mulang

- spec/InspectorSpec.hs
- src/Language/Mulang/Inspector.hs
> Issue #24 parses expectation

- mulang.cabal
- spec/ExpressivenessSpec.hs
- src/Control/Fallible.hs
- src/Language/Mulang/Binding.hs
- src/Language/Mulang/Cli/Compiler.hs
- src/Language/Mulang/Explorer.hs
- src/Language/Mulang/Inspector.hs
- src/Language/Mulang/Inspector/Combiner.hs
- src/Language/Mulang/Inspector/Expressiveness.hs
- src/Language/Mulang/Inspector/Extras.hs
- src/Language/Mulang/Parsers.hs
- src/Language/Mulang/Parsers/Haskell.hs
- src/Language/Mulang/Parsers/JavaScript.hs
- src/Language/Mulang/Parsers/Json.hs
- src/Language/Mulang/Parsers/Prolog.hs
- src/Text/Inflections/Tokenizer.hs
- src/Text/SimpleParser.hs
> Expressiveness check foundations

- spec/InspectorSpec.hs
- src/Language/Mulang/Inspector.hs
- src/Language/Mulang/Parsers/Haskell.hs
Fixes mumuki/mumuki-haskell-server#3
Fixes #37
> Traversing patterns tree

- spec/InspectorSpec.hs
- src/Language/Mulang/Parsers/Haskell.hs
Fixes mumuki/mumuki-haskell-server#2
> Adding newline to HS code before analyzing

- spec/JsInspectorSpec.hs
- src/Language/Mulang/Inspector.hs
- src/Language/Mulang/Inspector/Smell.hs
> Is long code

- README.md
- mulang.cabal
- spec/AnalysisJsonSpec.hs
- spec/SmellsAnalyzerSpec.hs
- src/Language/Mulang/Analyzer.hs
- src/Language/Mulang/Analyzer/Analysis.hs
- src/Language/Mulang/Analyzer/Analysis/Json.hs
- src/Language/Mulang/Analyzer/SmellsAnalyzer.hs
- src/Main.hs
> Adding  SmellsSet

- README.md
- mulang.cabal
- spec/AnalysisJsonSpec.hs
- spec/SmellsAnalyzerSpec.hs
- src/Language/Mulang/Analyzer.hs
- src/Language/Mulang/Analyzer/Analysis.hs
- src/Language/Mulang/Analyzer/SignaturesAnalyzer.hs
- src/Language/Mulang/Analyzer/SmellsAnalyzer.hs
- src/Text/Inflections/Tokenizer.hs
> Chore cleanup

- README.md
- spec/SmellSpec.hs
- src/Language/Mulang/Inspector/Generic/Smell.hs
> Feature extend redundant if to assignments

- spec/GobstonesSpec.hs
- src/Language/Mulang/Parsers/Gobstones.hs
Refactored Gobstones Parser and added and parsing  `return` in programs.
> Fix add return in program

- README.md
- spec/ExpectationsCompilerSpec.hs
- spec/InspectorSpec.hs
- src/Language/Mulang/Analyzer/ExpectationsCompiler.hs
- src/Language/Mulang/Binding.hs
Adding support for any-of binding predicates.
> Supporting anyOf

- README.md
- spec/InspectorSpec.hs
- spec/JavaSpec.hs
- spec/SmellSpec.hs
- src/Language/Mulang/Analyzer/Analysis.hs
- src/Language/Mulang/Analyzer/ExpectationsCompiler.hs
- src/Language/Mulang/Analyzer/SmellsAnalyzer.hs
- src/Language/Mulang/Ast.hs
- src/Language/Mulang/Inspector/Generic.hs
- src/Language/Mulang/Inspector/Generic/Smell.hs
- src/Language/Mulang/Parsers/Haskell.hs
- src/Language/Mulang/Parsers/Java.hs
- src/Language/Mulang/Parsers/JavaScript.hs
:warning:  Work In Progress
Fixes #92 
Fixes #6 
Fixes #79
> Adding Rescue, Raise and Print

- spec/ExpectationsCompilerSpec.hs
- src/Language/Mulang/Parsers/Java.hs
> Properly transforming variables into attributes

- spec/ExpectationsAnalyzerSpec.hs
- spec/ExpectationsCompilerSpec.hs
- src/Language/Mulang/Analyzer/ExpectationsCompiler.hs
> Feature binding wildcard

- README.md
- spec/ExpectationsCompilerSpec.hs
- spec/InspectorSpec.hs
- src/Language/Mulang/Analyzer/ExpectationsCompiler.hs
- src/Language/Mulang/Inspector/Generic.hs
> Feature calls

- app/Main.hs
- mulang.cabal
- spec/AnalysisJsonSpec.hs
- spec/SmellsAnalyzerSpec.hs
- src/Language/Mulang/Analyzer/Analysis.hs
- src/Language/Mulang/Analyzer/Analysis/Json.hs
- src/Language/Mulang/Analyzer/SmellsAnalyzer.hs
Fixes #43
Fixes mumuki/mumuki-platform/issues/295
> Fix wrong smells error reporting

- spec/ExpectationsCompilerSpec.hs
- src/Language/Mulang/Ast.hs
- src/Language/Mulang/Generator.hs
- src/Language/Mulang/Inspector/Generic.hs
> Issue#115 uses expectation not working properly

- README.md
Improving Mulang documentation
> Chore improved documentation

- spec/DomainLanguageSpec.hs
- src/Text/Inflections/Tokenizer.hs
> Issue #123 ruby case not accepting special chars

- spec/SmellSpec.hs
- src/Language/Mulang/Generator.hs
- src/Language/Mulang/Inspector/Generic/Smell.hs
> Issue#122 point free is suggested even if parameter appears more than once

- spec/InspectorSpec.hs
- src/Language/Mulang/Generator.hs
> Issue #112 new not properly handled

- spec/ExpectationsAnalyzerSpec.hs
- spec/ExpectationsCompilerSpec.hs
- src/Language/Mulang/Generator.hs
> Issue#129 expectations fail on assignment

- spec/JavaScriptSpec.hs
- src/Language/Mulang/Parsers/JavaScript.hs
- stack.yaml
> Update parser to latest version and implement new AST conversion

- src/Language/Mulang/Ast.hs
- src/Language/Mulang/Generator.hs
- src/Language/Mulang/Parsers/Haskell.hs
- src/Language/Mulang/Parsers/Java.hs
- src/Language/Mulang/Parsers/JavaScript.hs
Please review but **do not** merge.
This is a non-backward compatible change to be merged after #98
> Replacing Other with Unknown

- README.md
- spec/ExpectationsAnalyzerSpec.hs
- spec/ExpectationsCompilerSpec.hs
- spec/InspectorSpec.hs
- spec/JavaScriptSpec.hs
- spec/JavaSpec.hs
- src/Language/Mulang/Analyzer/ExpectationsCompiler.hs
- src/Language/Mulang/Ast.hs
- src/Language/Mulang/Builder.hs
- src/Language/Mulang/Generator.hs
- src/Language/Mulang/Inspector/Procedural.hs
- src/Language/Mulang/Parsers/Java.hs
- src/Language/Mulang/Parsers/JavaScript.hs
> Issue#156 add c style for support

- gem/lib/mulang/language.rb
- gem/spec/mulang_spec.rb
Fixes mumuki/mumuki-laboratory#1043.
> Rescue parse failure and return nil

- spec/SmellSpec.hs
- src/Language/Mulang/Inspector/Generic/Smell.hs
> Issue##144 fix empty list exception

- spec/SmellsAnalyzerSpec.hs
- src/Language/Mulang/Analyzer/SmellsAnalyzer.hs
> Issue#171 add empty if branches smell to smells analysis

- spec/PrologSpec.hs
- src/Language/Mulang/Parsers/Prolog.hs
Fixes mumuki/mumuki-prolog-runner#32.
> Issue mumuki/mumuki prolog runner#32 misdetected has redundant reduction smell

- README.md
- spec/HaskellSpec.hs
- spec/JavaSpec.hs
- src/Language/Mulang/Ast.hs
- src/Language/Mulang/Inspector/Generic/Duplication.hs
- src/Language/Mulang/Parsers/Haskell.hs
- src/Language/Mulang/Parsers/Java.hs
> Issue#189 chars and single char strings should be different

- spec/SmellSpec.hs
- src/Language/Mulang/Inspector/Generic/Smell.hs
Fixes #197.
Sorry, I know I shouldn't be doing context changes! :cry:
> Issue#197 has unreachable code is misdetected

- README.md
- spec/ExpectationsCompilerSpec.hs
- spec/InspectorSpec.hs
- src/Language/Mulang/Analyzer/ExpectationsCompiler.hs
- src/Language/Mulang/Inspector/Procedural.hs
> Feature add uses loop expectation

- .gitignore
- ghcjslib/deploy.sh
- ghcjslib/package.json
- stack.yaml
- stack.yaml.ghcjs
- tag.sh
> Publish with npm

- README.md
- app/Main.hs
- ghcjslib/README.md
- ghcjslib/test.sh
- ghcjslib/test/test.js
- spec/AnalysisJsonSpec.hs
- spec/JavaScriptSpec.hs
- spec/Spec.hs.ghcjs
- src/Language/Mulang/Parsers/JavaScript.hs
- stack.yaml
- stack.yaml.ghcjs
> Using latest javascript

- spec/PrologSpec.hs
- src/Language/Mulang/Parsers/Prolog.hs
Fixes mumuki/mumuki-prolog-runner#35.
> Fix mumuki/mumuki-prolog-runner#35 analysis fails when there are comments

- README.md
- spec/PythonSpec.hs
- src/Language/Mulang/Analyzer/Analysis.hs
- src/Language/Mulang/Analyzer/FragmentParser.hs
- src/Language/Mulang/Parsers/Python.hs
Introducing `Python3` - a synonym of `Python` - and `Python2`
> Adding support for python2

- spec/SmellSpec.hs
- src/Language/Mulang/Inspector/Generic/Smell.hs
Improving this code smell to also detect code after return. 
Rebase after #262
> Feature improved unreachable code smell

- mulang.cabal
- spec/AutocorrectorSpec.hs
- src/Language/Mulang/Analyzer/Autocorrector.hs
- src/Language/Mulang/Operators/JavaScript.hs
Ups, I had completely forgotten about JS tokens table :sweat_smile: 
@fedescarpa please check this PR, you will have to do the same in C if you want to make things like `Uses:+` work.
> Adding missing tokens table

- CHANGELOG.md
- docs/clispec.md
- docs/index.md
- docs/inspections.md
- docs/js/trymulang.js
- docs/try.md
- release.sh
> Chore update docs

- spec/JavaScriptSpec.hs
- src/Language/Mulang/Parsers/JavaScript.hs
To fix several parsing issues related with field access, field assignment, call and send interactions. 
* Fixes #322. 
* Fixes other non previously detected issues.
> Fix #322 parsing of js call expressions

- spec/JavaScriptSpec.hs
- stack.yaml
- stack.yaml.lock
Fix odd behavior in js parser where comments would affect the resulting AST's semantics.
Fixes https://github.com/mumuki/mulang/issues/338.
@flbulgarelli I'm assigning you because you fixed the parser bug :smile:, once that's merged hopefully this should just need updating and merging.
> Issue#338 comments affect js semantics

- docs/astspec.md
- gem/spec/i18n_spec.rb
- spec/AutocorrectorSpec.hs
- spec/FunctionalSpec.hs
- spec/PythonSpec.hs
- src/Language/Mulang/Ast/Operator.hs
- src/Language/Mulang/Parsers/Python.hs
- tokens.yml
To improve Python support
Support was added for the following features:
* Slice operator
* Size operator 
* `global` declaration
* `del`
*  `break`
*  `continue`
* Inline if expressions support
Also, support for comprehensions was extended and improved. 
Fixes https://github.com/mumuki/mulang/issues/335
> Feature misc python improvements
