README.md, mulang.cabal, mulang_pp, spec/CliSpec.hs, spec/SignatureSpec.hs, src/Language/Mulang/Ast.hs, src/Language/Mulang/Cli/Code.hs, src/Language/Mulang/Cli/Compiler.hs, src/Language/Mulang/Cli/Interpreter.hs, src/Language/Mulang/Explorer.hs, src/Language/Mulang/Inspector/Generic.hs, src/Language/Mulang/Inspector/Generic/Duplication.hs, src/Language/Mulang/Parsers/Haskell.hs, src/Language/Mulang/Signature.hs
Fixes #57
This PR adds initial support for signature analysis. Current signature format is hardcoded, it resembles haskell, prolog and js code signatures, but it does not intend to produce language-sensitive signatures. It may be addressed in a future PR. 
Some samples: 
```bash
$ mulang '
{
"code" : {
"content" : "function foo(x, y) { return x + y; }\nfunction bar(z) { return z * 2; }",
"language" : "JavaScript"
},
"expectations" : [],
"analyseSignatures" : true
}' | json_pp
{
"smells" : [],
"results" : [],
"signatures" : [
"foo(x, y)",
"bar(z)"
]
}
```
```bash
$ mulang '
{
"code" : {
"content" : "foo(X, Y) :- m(X), b(Y).",
"language" : "Prolog"
},
"expectations" : [],
"analyseSignatures" : true
}' | json_pp
{
"results" : [],
"signatures" : [
"foo/2"
],
"smells" : []
}
```
```bash
mulang …
```
=> Feature signatures

spec/DomainLanguageSpec.hs, spec/SmellsAnalyzerSpec.hs, src/Language/Mulang/Analyzer.hs, src/Language/Mulang/DomainLanguage.hs, src/Language/Mulang/Generator.hs
Domain Language analysis, since it is performed over identifiers
and not whole expressions, may arise confusing results if evaluated
with normal 'is-or-contains' semantics.
=> Perform domain smells analysis only on main expressions

README.md, spec/SmellSpec.hs, src/Language/Mulang/Analyzer/SmellsAnalyzer.hs, src/Language/Mulang/Inspector/Generic/Smell.hs
Fixes #66
It is somewhat limited since it can actually only detect this case:
if(condition){
} else {
something();
}
Detecting an empty else is impossible without further distinguishing between the lack of an else body and the lack of an else altogether.
=> Add empty if branches smell

README.md, spec/InspectorSpec.hs, spec/JavaSpec.hs, src/Language/Mulang/Ast.hs, src/Language/Mulang/Inspector/Generic.hs, src/Language/Mulang/Parsers/Haskell.hs, src/Language/Mulang/Parsers/Java.hs, src/Language/Mulang/Parsers/JavaScript.hs, src/Language/Mulang/Signature.hs
Merge after #105 
Fixes #93
This PR adds support for the following inspections: 
* `typesReturnAs`
* `typesParameterAs`
* `typesAs`
* `usesType`
=> Feature Typed Inspections

mulang.cabal
It appears that the inflections API changed somewhat as of 0.3.0.0, and while the stack lts-7.24 resolver gives the right version, building with cabal alone may fail (and this may be why hackage lists mulang as failing to build).
=> Force older version of inflections library

spec/HaskellSpec.hs, src/Language/Mulang/Ast.hs, src/Language/Mulang/Parsers/Haskell.hs
Fixes #177 
The issue was actually only with literal patterns. In the future, we should refactor the `LiteralPattern` element to actually accept and expression instead of just code
=> Issue #177 haskell literal patterns are ignored

README.md, ghcjslib/build.sh, ghcjslib/test.sh, spec/Spec.hs.ghcjs
Generating `Spec.hs` automatically in ghcjslib build, and simplifying build instructions
=> Improving ghcjslib build script

spec/AnalysisJsonSpec.hs, spec/ExpectationsAnalyzerSpec.hs, spec/NormalizationSpec.hs, spec/SmellsAnalyzerSpec.hs, spec/Spec.hs.ghcjs, src/Language/Mulang/Analyzer/Analysis.hs, src/Language/Mulang/Analyzer/Analysis/Json.hs, src/Language/Mulang/Analyzer/SampleParser.hs, src/Language/Mulang/Ast.hs, src/Language/Mulang/Builder.hs, src/Language/Mulang/Parsers/Haskell.hs, src/Language/Mulang/Parsers/Java.hs, src/Language/Mulang/Parsers/JavaScript.hs
:warning: Work In Progress
This PR allows mulang to
* generate the same ASTs if two solutions have the same contents but declarations are in different order
* expose the normalization API to the CLI, so that external generators can use it
* finer-grained customization of the normalization process
*Pending tasks*: 
* ~Add docs~ will be addressed in #184
* ~Add tests~
* ~Maybe we should ensure that reordering only occurs when there are no duplicated name declarations~
=> Feature reordering

README.md, spec/SmellSpec.hs, src/Language/Mulang/Analyzer/SmellsAnalyzer.hs, src/Language/Mulang/Inspector/Generic/Smell.hs
Fixes #188.
This is kind of a simplistic implementation for now. There are probably a bunch of other cases which should be detected, like sentences after a non-conditional return, or probably other pattern matching cases.
=> Issue#188 add has unreachable code smell

spec/InspectorSpec.hs, src/Language/Mulang/Inspector/Generic.hs
The current semantics was not compatible with javascript and python.
=> Extending raises semantics

spec/JavaScriptSpec.hs, spec/JavaSpec.hs, spec/PythonSpec.hs, spec/SmellSpec.hs, src/Data/List/Extra.hs, src/Language/Mulang/Parsers/Java.hs, src/Language/Mulang/Parsers/JavaScript.hs, src/Language/Mulang/Parsers/Python.hs
Some commits were extracted from #232 
Fixes: 
* removing odd quotes in python strings
* properly parsing python's `print`
* properly parsing javascript's `console.log`
* parsing Java initializers
* supporting booleans in python 2
=> Miscellaneous fixes to java, javascript and python parsers  

spec/CombinerSpec.hs, spec/SmellsAnalyzerSpec.hs, src/Language/Mulang/Analyzer/SmellsAnalyzer.hs, src/Language/Mulang/Inspector/Combiner.hs
Depends on #235 
Currently, smells can only be detected if they occur within a declaration. This PR adds support for detecting smells at top-level, too.
=> Introducing locate and top-level smells

README.md, spec/ExpectationsCompilerSpec.hs, spec/InspectorSpec.hs, spec/LiteralSpec.hs, src/Language/Mulang/Analyzer/ExpectationsCompiler.hs, src/Language/Mulang/Inspector/Literal.hs, src/Language/Mulang/Inspector/Matcher.hs
This is non-backward compatible refactor of literal expectations, that aims them to be translated easily to natural language using https://github.com/mumuki/mumukit-inspection. 
Although this is a breaking change, I propose to be merged as a micro version, since this feature has just been released a few days ago and it should be considered still experimental. 
In the future, we should mark which packages are experimental and which not.
=> Refactor assignments exposure

gem/spec/mulang_spec.rb, spec/CustomExpectationsAnalyzerSpec.hs, src/Language/Mulang/Analyzer.hs, src/Language/Mulang/Analyzer/Analysis.hs, src/Language/Mulang/Analyzer/Analysis/Json.hs, src/Language/Mulang/Analyzer/CustomExpectationsAnalyzer.hs
In order to allow better interopelability with original expectations. 
With this change, instead of returning a separate list, custom expectation results are reported the following way: 
```edl
test "must assign something": 
assigns;
```
```ruby
{ expectation: { binding: "<<custom>>", inspection: "must assign something"  }, result: true }
```
=> Adding custom expectation results to standard list

gem/lib/mulang/code.rb, gem/lib/mulang/expectation.rb, gem/lib/mulang/expectation/custom.rb, gem/lib/mulang/expectation/standard.rb, gem/lib/mulang/inspection.rb, gem/lib/mulang/inspection/matcher.rb, gem/spec/i18n_spec.rb, gem/spec/inspection_spec.rb, gem/spec/mulang_spec.rb
Adding support for Custom Inspections internationalization, which was missing. 
Code was refactored to support it and a bug in `expect` was fixed.
=> Fix custom expectations i18n

spec/ExpectationsAnalyzerSpec.hs, spec/InspectorSpec.hs, src/Language/Mulang/Analyzer/EdlQueryCompiler.hs, src/Language/Mulang/Inspector/Combiner.hs
Fixes #249 
dot-syntax never worked - by design - with transitive inspections. So instead of making it fail silently, i am changing the implementation so it slips to scopedList when necessary
=> Fix dot syntax misbehavior with transitive bindings

docs/index.md
In the **Contributors** section, **mumuki** and **10pines** links redirect to 404 pages.
In the **Predicates** section:
> Notice: like in Mulang means that it contains that case-insensitive substring
I think this could be better explained by emphasizing the use of **~** like in the second example [here](https://mumuki.github.io/mulang/edlspec/#predicates)
=> Corrected some typos

spec/SmellSpec.hs, src/Language/Mulang/Inspector/Generic/Smell.hs
Now also mulang will report code like this: 
```javascript
function esPar(n){
if (n%2==0){
return true
} 
return false
}
```
=> Extending expectation to unstructured boolean ifs

spec/JavaScriptSpec.hs, src/Language/Mulang/Parsers/JavaScript.hs, stack.yaml, stack.yaml.ghcjs
This PR updates the `language-javascript` dependency, which comes with several improvement to ECMA6 support. However, the main motivation of this update is to fix a parsing bug about parenthesis around identifiers. 
I had to add a patch to our own for of this dependency since it was not compiling with `ghc-8.0.1`: https://github.com/mumuki/language-javascript/commit/1fc93bb2aec122f4eefd2fd9dc2849d9001f6ea5
Fixes #276
=> Updating js-dep version

spec/SmellsAnalyzerSpec.hs, src/Language/Mulang/Analyzer/SmellsAnalyzer.hs
Smells could be duplicated because of the following reasons:
- Context-sensitive smells could be activated more than once
- Smells that apply to type signatures would be activated twice in most cases - because of the type signature and the declaration
I am adding nub to the smells pipeline
=> Removing duplicates in smells

mulang.cabal, spec/InterpreterSpec.hs, src/Language/Mulang/Interpreter.hs, src/Language/Mulang/Interpreter/Internals.hs
Those are just minor refactors to the interpreter: 
* An `Internals` module has been extracted, with the internal data structures used by the interpereter
* `typeErrors` and primitive operator wrappers have being _slightly_ reifiyed
Also the python ignored tests were already passing. 
Some notes: 
* the `Internals` module contains the `ExecutionContext` and `Value` definitions which are currently core to the interpreter and exposed to any consumer of it. I am planning to hide them in the future with the introduction of a `Repl` module that complements the `Runner` module. 
Also, I want to make primitives to be easy to implement since I am planning to introduce more of them. See #286
=> Feature interpreter refactor

docs/edlspec.md, gem/spec/i18n_spec.rb, spec/CounterSpec.hs, spec/CustomExpectationsAnalyzerSpec.hs, spec/ExpectationsCompilerSpec.hs, spec/GenericSpec.hs, src/Language/Mulang/Analyzer/Autocorrector.hs, src/Language/Mulang/Analyzer/EdlQueryCompiler.hs, src/Language/Mulang/Inspector/Generic.hs
`Returns` inspection support was quite limited - it could not be counted nor used without a matcher. This PR make it a first class citizen.
=> Improve return support

src/Language/Mulang/Ast/Operator.hs
Related to https://github.com/mumuki/mulang/issues/242
Related to https://github.com/mumuki/mulang/issues/7
This PR only introduces new operators but does not document them nor includes any implementation of them. It is just for internal documentation purposes and to serve as harness to new inspections and language support. 
I am adding some basic non-trivial non-trigonometric math operators that can be typically found on a `Math` module, plus a list of common collection handling  operators. I am using classic Smalltalk naming - I considered using haskell naming but `Map` will collide too-often collide with `Data.Map` :unamused:
=> Adding operators for collections and numbers

spec/ObjectOrientedSpec.hs, spec/SmellSpec.hs, src/Language/Mulang/Analyzer/SmellsAnalyzer.hs, src/Language/Mulang/Inspector/Generic/Smell.hs
Fixes https://github.com/mumuki/mulang/issues/296.
I've discussed this with @flbulgarelli but this is not a perfect solution, especially when it comes to ruby.
In ruby it's pretty hard to programatically pinpoint what context a certain expression is run in, such as how in:
```ruby
module Pepita
def self.foo
some_other_object.instance_eval { do_something_with Pepita }
end
end
```
`Pepita` can't be replaced for `self` since that block is run in another object's context.
Yet another problem in ruby is that objects can be nested, so here:
```ruby
module Aves
module Pepita
self
end
end
```
`self` references `Aves::Pepita`, and if one wanted to reference `Aves`, they'd have to do it by name.
As a compromise solution, we've decided to only look for named self references in an object's methods, …
=> Feature uses named self reference smell

docs/clispec.md, docs/js/trymulang.js, docs/try.md, gem/lib/mulang/code.rb, gem/lib/mulang/language.rb, gem/spec/mulang_spec.rb, ghcjslib/src/code.js, spec/AnalysisJsonSpec.hs, spec/NormalizationSpec.hs, src/Data/List/Extra.hs, src/Language/Mulang/Analyzer/Analysis/Json.hs, src/Language/Mulang/Builder.hs, src/Language/Mulang/Inspector/Literal.hs
To allow to introduce implicit returns in some languages - e.g. ruby. 
* https://github.com/mumuki/mulang/issues/295
=> Feature return normalization

mulang.cabal, spec/AnalysisJsonSpec.hs, spec/NormalizerSpec.hs, spec/RenamerSpec.hs, src/Language/Mulang/Analyzer/Analysis.hs, src/Language/Mulang/Analyzer/Analysis/Json.hs, src/Language/Mulang/Analyzer/FragmentParser.hs, src/Language/Mulang/Ast/Visitor.hs, src/Language/Mulang/Builder.hs, src/Language/Mulang/Generator.hs, src/Language/Mulang/Parsers/C.hs, src/Language/Mulang/Parsers/Haskell.hs, src/Language/Mulang/Parsers/Java.hs, src/Language/Mulang/Parsers/JavaScript.hs, src/Language/Mulang/Parsers/Prolog.hs, src/Language/Mulang/Parsers/Python.hs, src/Language/Mulang/Renamer.hs, src/Language/Mulang/Transform/Normalizer.hs, src/Language/Mulang/Transform/Renamer.hs
To allow mulang to generate more abstract representations of code structure where names are less important
This PR just introduced the `Renamer`  module and refactors the `Normalizer` to generalize the concept of transforms, but does not actually use the rename code. It will be wired in coming-soon PRs. 
Rebase after #301
=> Feature renamer

spec/JavaScriptSpec.hs, src/Language/Mulang/Parsers/JavaScript.hs
To fix a long standing parsing issue with JS code related to decimal numbers format, that was not only not producing a valid AST, but also was breaking the mulang tool itself because of not having a proper error handling code. In fact, it was responsible for all `Prelude.read no parse` errors. 
Rebase after #301
=> Fix js decimal parsing error

app/Main.hs, gem/lib/mulang.rb, gem/lib/mulang/code.rb, gem/spec/mulang_spec.rb, src/Language/Mulang/Analyzer.hs
To allow batch processing of many  `Analysis` objects, which is a huge performance boost when using Mulang from ruby bindings.  
In my machine, this PR made mulang run 20 times faster in batch mode with 5K code snippets: 
```ruby
codes = 5000.times.map { |it| Mulang::Code.native("JavaScript", "let x = #{it}") }
Benchmark.measure { codes.map(&:ast) }
=> #<Benchmark::Tms:0x0000559f26f40888
@cstime=2.2249019999999997,
@cutime=6.524682,
@label="",
@real=8.298607618999085,
@stime=0.47271799999999997,
@total=9.968713,
@utime=0.7464109999999999>
Benchmark.measure { Mulang::Code.ast_many codes }
=> #<Benchmark::Tms:0x0000559f27d208b8
@cstime=0.01631700000000036,
@cutime=0.26108499999999957,
@label="",
@real=0.49491714800024056,
@stime=0.004264999999999963,
@total=0.5073949999999998, …
```
=> Feature batch mode

app/Main.hs, gem/lib/mulang.rb, gem/lib/mulang/code.rb, gem/lib/mulang/language.rb, gem/spec/mulang_spec.rb, mulang.cabal, spec/SerializerSpec.hs, src/Language/Mulang/Analyzer.hs, src/Language/Mulang/Analyzer/Analysis.hs, src/Language/Mulang/Analyzer/Analysis/Json.hs, src/Language/Mulang/Serializer.hs
To allow alternative serializations of AST, in modes accepted by other tools from the Ruby interface: 
* [labelled bracket notation](http://www.glottopedia.org/index.php/Labeled_bracketing)
* labelled brace notation
The first one - which is quite standard - can be used in tools like [this](http://www.tycho.iel.unicamp.br/phpsyntaxtree/) or [this](http://mshang.ca/syntree/) to render a tree like this... 
..or this: 
The latter - which seems to be pretty rare - can be used with [this tool](https://pypi.org/project/apted/)
In the future, we may add formats like [Newick](https://en.wikipedia.org/wiki/Newick_format) or S-expression too.  
You can activate serialization using the `serialization` argument from Ruby interface:
```ruby
> code = Mulang::Code.native('JavaScript', 'let x = 1; …
```
=> Feature ast serialization

src/Language/Mulang/Ast.hs, src/Language/Mulang/Ast/Visitor.hs, src/Language/Mulang/Inspector/Smell.hs
Dropping support for `Equal`, `NotEqual`, `HashMethod` and `EqualMethod`.  They were deprecated long ago
=> Removing deprecated AST elements

spec/TransformerSpec.hs, src/Language/Mulang/Analyzer/Analysis.hs, src/Language/Mulang/Analyzer/Analysis/Json.hs, src/Language/Mulang/Analyzer/Transformer.hs, src/Language/Mulang/Transform/Cropper.hs, src/Language/Mulang/Transform/Replacer.hs
Allow replace and crop to optionally work only at a given scope - either `GlobalScope` or `LocalScope` - using new operation variants `CropAt` and `ReplaceAt`: 
```ruby
Mulang::Code.transformed_asts_many(codes, [
[
{tag: :CropAt, contents: [ :GlobalScope, "IsVariable" ]}
]
])
```
=> Feature scoped replacer

gem/lib/mulang/code.rb, gem/lib/mulang/language.rb, gem/spec/mulang_spec.rb, src/Language/Mulang/Analyzer.hs, src/Language/Mulang/Analyzer/Analysis.hs
To allow declared and references identifiers to be extracted as part of analysis.
```ruby
> code = Mulang::Code.native('JavaScript', 'let x = 1; function m(a, b) { return a + b + x }')
> code.identifiers
=> [["x", "m"], ["a", "b", "x"]] }
```
Rebase after #310
=> Feature identifiers analysis

gem/lib/mulang/language.rb, gem/spec/mulang_spec.rb
To allow `External` languages to be serialized, since `ast` method returns them as-is otherwise. 
See discussion about this PR [here ](https://github.com/mumuki/mulang/pull/312#discussion_r560382012)
=> Allow serialization of external languages

spec/AutocorrectorSpec.hs, src/Language/Mulang/Analyzer/Analysis.hs, src/Language/Mulang/Analyzer/Autocorrector.hs
Allow autocorrection subsystem to work with `MulangSample` when an original true language can not be given - and as a consequence - can nor inferred.
```ruby
Mulang::Code.external(tag: :None) {|it|it}.analyse expectations: [{binding: "*", inspection: "Uses:foo"}], autocorrectionRules: {"Uses:foo" => "UsesIf"}
=> {"outputIdentifiers"=>nil,
"tag"=>"AnalysisCompleted",
"testResults"=>[],
"signatures"=>[],
"transformedAsts"=>nil,
"smells"=>[],
"expectationResults"=>[{"result"=>false, "expectation"=>{"inspection"=>"Uses:foo", "binding"=>"*"}}],
"outputAst"=>nil}
```
```ruby
Mulang::Code.external(tag: :None) {|it|it}.analyse expectations: [{binding: "*", inspection: "Uses:foo"}], autocorrectionRules: {"Uses:foo" => "UsesIf"}
=> {"outputIdentifiers"=>nil,
"tag"=>"AnalysisCompleted", …
```
=> Infer language from mulang sample

spec/NormalizerSpec.hs, src/Language/Mulang/Transform/Normalizer.hs
To avoid adding an implicit return on `MuNil`, since otherwise it may generate unintended smelly code - which will be reported as a `ReturnsNil`
In the future we have a more stricter variant of this normalization, but for now I think it is a good tradeof. 
* https://github.com/mumuki/mulang/issues/295
* https://github.com/mumuki/mulang/pull/298
=> Avoid introducing implicit return on nil

spec/AutocorrectorSpec.hs, src/Language/Mulang/Analyzer/Synthesizer.hs
This is a fix to a severe issue regarding autocorrection rules - the multiply operator is hiding the wildcard asterisk in `Uses:*` and `Declares:*`.  The solution here is to just don't generate autocorrection rules for this token. 
This PR adds support for strict matching (`=`) with autocorrection rules, and a few exceptions for wildcard asterisk `*` and operators that start with `=`. 
* `Uses:$token`
* `Uses:=$token`
* `Not:Uses:$token`
* `Not:Uses:=$token`
* `Declares:$token`
* `Declares:=$token`
* `Not:Declares:$token`
* `Not:Declares:=$token`
* `Uses:=*`
* `Not:Uses:=*`
* `Declares:=*`
* `Not:Declares:=*`
E.g `===`: 
* `Uses:====`
* `Not:Uses:====`
* `Declares:====`
* `Not:Declares:====`
Notice the additional fourth `=` .
=> Fix multiply operator hides wildcard

gem/lib/mulang/code.rb, gem/lib/mulang/language.rb, gem/spec/mulang_spec.rb
:dart: Goal
To allow passing `originalLanguage` to all specs in `Mulang::Language::External`. This is necessary to activate language-specific autocorrection rules - currently this is only true for `Ruby` and `Php`
=> Accept and use originalLanguage in External

gem/lib/mulang/expectation.rb, spec/SmellSpec.hs, src/Language/Mulang/Inspector/Smell.hs
To promote this smell to general smells set, and to make it work with callables longer than  2 statements.
=> Fixes to HasRedundantVariableReturn

spec/JavaSpec.hs, src/Language/Mulang/Parsers/Java.hs
Assignments to own attributes were not being properly parsed. This PR fixes this.
=> Fix parsing of assignment to this in Java

docs/edlspec.md, docs/inspections.md, spec/CustomExpectationsAnalyzerSpec.hs, src/Language/Mulang/Analyzer/EdlQueryCompiler.hs, src/Language/Mulang/Inspector/Family.hs, src/Language/Mulang/Inspector/Generic.hs
Add support for counting `uses` and `usesPrimtive`. Otherwise there are no equivalents of counting operators that became primitives in mulang 6
=> Chore improve backwards compatibility

spec/AutocorrectorSpec.hs, tokens.yml
To add `Size` operator support to Ruby.
Fixes https://github.com/mumuki/mulang/issues/323
=> Add ruby size operators

gem/lib/mulang/expectation.rb, gem/spec/format_spec.rb, spec/ObjectOrientedSpec.hs
To fix parsing of expectations when they contain the sequence `Has` in places different than the start. 
_How much damage can a single ^ do?_ :facepalm:
=> Fix #324 hash map inspection

gem/lib/mulang/code.rb, gem/lib/mulang/language.rb, gem/spec/mulang_spec.rb, spec/AnalysisJsonSpec.hs, spec/AutocorrectorSpec.hs, spec/ExpectationsAnalyzerSpec.hs, spec/SmellsAnalyzerSpec.hs, src/Language/Mulang/Analyzer/Analysis.hs, src/Language/Mulang/Analyzer/FragmentParser.hs
To fix issues related with the ruby interface:
* original language of external languages was not used in the `analyse` and `analysis` methods
* passing `nil` ast the ast produced severe parsing errors at mulang core. This a big pain in the neck when using the batch mode and the external tool can not parse the source code.
=> Fix external languages fixes

docs/astspec.md, spec/GenericSpec.hs, spec/PythonSpec.hs, src/Language/Mulang/Ast.hs, src/Language/Mulang/Ast/Visitor.hs, src/Language/Mulang/Generator.hs, src/Language/Mulang/Inspector/Functional.hs, src/Language/Mulang/Inspector/Primitive.hs, src/Language/Mulang/Inspector/Smell.hs, src/Language/Mulang/Parsers/Python.hs, src/Language/Mulang/Signature.hs, src/Language/Mulang/Transform/Renamer.hs
Add support for named arguments and parameters with default value
Two new AST elements have been added: `As` and `DefaultPattern`. Only the latter has been documented, since `As` may change in the near feature. Also, some typos have been fixed in the process.
=> Feature parse keyword arguments

docs/edlspec.md, docs/index.md, docs/inspections.md, gem/lib/locales/en.yml, gem/lib/locales/es.yml, gem/lib/locales/pt.yml, gem/lib/mulang/inspection.rb, gem/lib/mulang/inspection/matcher.rb, gem/spec/i18n_spec.rb, gem/spec/inspection_spec.rb, generators/tokens.rb, spec/EdlSpec.hs, spec/ExpectationsCompilerSpec.hs, spec/GenericSpec.hs, src/Language/Mulang/Analyzer/EdlQueryCompiler.hs, src/Language/Mulang/Analyzer/ExpectationsCompiler.hs, src/Language/Mulang/Analyzer/Synthesizer.hs, src/Language/Mulang/Edl/Expectation.hs, src/Language/Mulang/Edl/Lexer.x, src/Language/Mulang/Edl/Parser.y, src/Language/Mulang/Inspector/Generic.hs, src/Language/Mulang/Inspector/Literal.hs, src/Language/Mulang/Inspector/Matcher.hs
To allow primitive calls to be checked using matchers
* Documentation updated
* A `WithReference` matcher was added 
* `WithAnything` matchers was supported as part of the plain inspections - although it will not be very useful yet. 
* Some typos were fixed.
=> Feature calls primitive

ghcjslib/release.sh, ghcjslib/src/main.js
La siguiente línea está trayendo problemas para proyectos donde se importe mulang.js directamente sin estar dentro de una carpeta, porque no encuentra el package.json:
https://github.com/mumuki/mulang/blob/6c04e3e1816eed8925e1bb152b8ac9c03608b02e/ghcjslib/src/main.js#L31-L33
Propuse reemplazarla en release time, no sé cómo resolverlo de otra forma.
=> Replacing ghcjslib's version at release time

spec/GenericSpec.hs, spec/NormalizerSpec.hs, src/Language/Mulang/Analyzer/Analysis/Json.hs, src/Language/Mulang/Normalizers/JavaScript.hs, src/Language/Mulang/Normalizers/Python.hs, src/Language/Mulang/Parsers/Python.hs, src/Language/Mulang/Transform/Normalizer.hs
To allow functions defined by parts to also be considered functions
A new normalization mode was introduced, and enabled by default in Python and JavaScript. Also, sorting of python expressions is more conservative now.
=> Feature normalize functions by parts
